class CreateLoanapps < ActiveRecord::Migration
  def self.up
    create_table :loanapps do |t|
      t.string :loan_type
      t.string :line_of_credit_limit
      t.string :credit_limit_increase
      t.string :initial_amount_requested
      t.string :purpose_of_loan
      t.string :collateral_offered
      t.string :owned_by
      t.string :type_of_credit
	  t.string :single_credit_life_insurance
	  t.string :single_credit_insurance_age
	  t.string :joint_credit_life_insurance
	  t.string :joint_credit_insurance_age
	  t.string :credit_disability_insurance
	  t.string :credit_disability_insurance_age
      t.string :applicant_name
      t.string :applicant_account_number
      t.string :applicant_ssn
      t.string :applicant_date_of_birth
      t.string :applicant_marital_status
      t.string :applicant_drivers_license
      t.string :applicant_drivers_license_state
      t.string :applicant_home_phone
      t.string :applicant_business_phone
      t.string :applicant_email_address
      t.string :applicant_address
      t.string :applicant_time_at_residence
      t.string :applicant_ownership
      t.string :applicant_mortgage_owed_to
      t.string :applicant_mortgage_balance
      t.string :applicant_monthly_payment
      t.string :applicant_current_apr
      t.string :applicant_responsible_for_payment
      t.string :applicant_total_monthly_payment
      t.string :applicant_total_monthly_balances
      t.string :applicant_employer
      t.string :applicant_income
      t.string :applicant_type_of_income
      t.string :applicant_salary_frequency
      t.string :applicant_other_income
      t.string :applicant_source_of_other_income
      t.string :applicant_other_income_frequency
      t.string :applicant_reference_name
      t.string :applicant_reference_phone_number
      t.string :applicant_reference_relationship
      t.string :applicant_reference2_name
      t.string :applicant_reference2_phone_number
      t.string :applicant_reference2_relationship
      t.string :applicant_previous_employer1_job_title
      t.string :applicant_previous_employer1_supervisor
      t.string :applicant_previous_employer1_hours_weekly
      t.string :applicant_previous_employer1_hourly_wages
      t.string :applicant_previous_employer1_salary_frequency
      t.string :applicant_previous_employer1_start_date
      t.string :applicant_previous_employer1_length_of_employment
      t.string :applicant_previous_employer2_job_title
      t.string :applicant_previous_employer2_supervisor
      t.string :applicant_previous_employer2_hours_weekly
      t.string :applicant_previous_employer2_hourly_wages
      t.string :applicant_previous_employer2_salary_frequency
      t.string :applicant_previous_employer2_start_date
      t.string :applicant_previous_employer2_length_of_employment
      t.string :coapplicant_name
      t.string :coapplicant_account_number
      t.string :coapplicant_ssn
      t.string :coapplicant_date_of_birth
      t.string :coapplicant_marital_status
      t.string :coapplicant_drivers_license
      t.string :coapplicant_drivers_license_state
      t.string :coapplicant_home_phone
      t.string :coapplicant_business_phone
      t.string :coapplicant_email_address
      t.string :coapplicant_address
      t.string :coapplicant_time_at_residence
      t.string :coapplicant_ownership
      t.string :coapplicant_mortgage_owed_to
      t.string :coapplicant_mortgage_balance
      t.string :coapplicant_monthly_payment
      t.string :coapplicant_current_apr
      t.string :coapplicant_responsible_for_payment
      t.string :coapplicant_total_monthly_payment
      t.string :coapplicant_total_monthly_balances
      t.string :coapplicant_employer
      t.string :coapplicant_income
      t.string :coapplicant_type_of_income
      t.string :coapplicant_salary_frequency
      t.string :coapplicant_other_income
      t.string :coapplicant_source_of_other_income
      t.string :coapplicant_other_income_frequency
      t.string :coapplicant_reference_name
      t.string :coapplicant_reference_phone_number
      t.string :coapplicant_reference_relationship
      t.string :coapplicant_reference2_name
      t.string :coapplicant_reference2_phone_number
      t.string :coapplicant_reference2_relationship
      t.string :coapplicant_previous_employer1_job_title
      t.string :coapplicant_previous_employer1_supervisor
      t.string :coapplicant_previous_employer1_hours_weekly
      t.string :coapplicant_previous_employer1_hourly_wages
      t.string :coapplicant_previous_employer1_salary_frequency
      t.string :coapplicant_previous_employer1_start_date
      t.string :coapplicant_previous_employer1_length_of_employment
      t.string :coapplicant_previous_employer2_job_title
      t.string :coapplicant_previous_employer2_supervisor
      t.string :coapplicant_previous_employer2_hours_weekly
      t.string :coapplicant_previous_employer2_hourly_wages
      t.string :coapplicant_previous_employer2_salary_frequency
      t.string :coapplicant_previous_employer2_start_date
      t.string :coapplicant_previous_employer2_length_of_employment

      t.timestamps
    end
  end

  def self.down
    drop_table :loanapps
  end
end
